### ISSUE TITLE
Figure out the basis of the fits names spit out by rts2

### ISSUE THREAD

**Issue by dsand** [so-artn/ARTN#12]
Right now, RTS2 naming scheme for fits files is a bit of a mystery.  here are some examples:

20171204001224-655-RA.fits
20171204005254-444-RA.fits

It is clear the first part is the date.  Less clear what '001224' or '655' or even what 'RA' are.  This will require interrogation of Petr, unless someone else knows?

**Comment by srswinde** [comment]
I added an rts2 value to the camera driver that will tell you what the path and name of the most recent exposure is.
