### ISSUE TITLE
Astroplan -- seems useful for planning observations

### ISSUE THREAD

**Issue by dsand** [so-artn/ARTN#14]
https://arxiv.org/pdf/1712.09631.pdf

This paper above came out on astroph tonight.  Seems like it has some useful functions for planning observations (including things like figuring out when the next transit of an exoplanet is, etc).  It may be good to incorporate in our 'brain' or higher-level scheduler.

Sorry, this is not an issue.  More of an FYI.

**Comment by bjweiner** [comment]
Yes, Duane Gibson at MMT is using astroplan as the basis of the MMT queue scheduler. It could be useful to talk to Duane and to Dallan Porter, who wrote a lot of the MMT queue observing web interface (which is pretty slick). One issue is that the scheduler really needs a ton of CPU on a fast machine to generate a long term schedule; I'm guessing this is a combo of having a complex optimization problem, and that astroplan must have routines in native python, which can be slow.
