### ISSUE TITLE
More monitors for ARTN

### ISSUE THREAD

**Issue by dsand** [so-artn/ARTN#37]
There are many windows needed to monitor ARTN+RTS2, we need more monitors.

Escalate this!

**Comment by tepickering** [comment]
i would recommend a pair of 32" 4k monitors. would fit well in current space and provide a huge increase in real estate for windows. they're not expensive, either. here's an example: https://www.newegg.com/samsung-lu32j590uqnxza-31-5-uhd/p/N82E16824022724

**Comment by dsand** [comment]
We bought two new monitors, but due to covid-19, dave took them back so people in his group could work from home.

I don't think we really need new monitors on the mountain, right?  We can reopen if necessary.
