### ISSUE TITLE
Out of sync 'Close Dome' and 'Close Mirror Cover' buttons

### ISSUE THREAD

**Issue by dsand** [so-artn/ARTN#43]
I arrived for night 2 of an ARTN run, with the 'Start Night' button already up and running.  However, the 'Close Dome' and 'Close Mirror Cover' buttons were up in red, even though both were already closed.  The fix was to close the 'Start Night' button, and restart by pressing the 'Safe Telescope Buttons' icon.

Scott said he can resolve this, easy peasy.

**Comment by danavner** [comment]
This was resolved with the new GUI. I'm going to close this issue.
