### ISSUE TITLE
Get AzCam to start remotely without the need for VNC.

### ISSUE THREAD

**Issue by dsand** [so-artn/ARTN#45]
This would be very useful if we are to enable remote observing.  Right now we need to vnc to bigccd and manually open AzCam.  It should just startup with ARTN scripts.

**Comment by davner** [comment]
After discussing this with Mike Lesser, he will include this option after summer shutdown 2020. He will also offer ways to monitor the instrument through an api.

**Comment by danavner** [comment]
This was completed with the azcam gui update.
