### ISSUE TITLE
Retire Issues prior to June 2020?

### ISSUE THREAD

**Issue by dsand** [so-artn/ARTN#49]
Wonder if we should retire all of our issues prior to June 2020, or archive them?  Just to clean up our issue list a bit and refocus our efforts on the tasks at hand.  

Thoughts, @danavner?  I wonder if there is a way to archive issues.

**Comment by tepickering** [comment]
the way i've seen this handled in the past is to create an `archived` label, tag the issues to archive with that, and then close them. that way you won't see them by default, but you can easily search for them by the label.

**Comment by dsand** [comment]
I like this.  I'll work on some more issues I need to generate to give @danavner some time to contribute.  And then I might just do it.

**Comment by danavner** [comment]
I like that idea as well. Let's move forward with it.

**Comment by dsand** [comment]
Done.  And closing this issue.  Victory.
