### ISSUE TITLE
startserver.sh and stopserver.sh

### ISSUE THREAD

**Issue by dsand** [so-artn/ARTN#52]
**Startserver.sh and stopservers.sh (anyone)**

- Test start-servers.sh in /remote-obs-website/project

     - Verify all servers were started 
     - Some are on gerard some on bigartn

- Test stop-servers.sh in /remote-obs-website/project

     - Verify all servers were stopped
     - Some are on gerard some on bigartn

[From email sent by Dan Avner 9/2/2020]

**Comment by danavner** [comment]
This was done in the December run. All servers can be stopped and started remotely with a click of a button on the webpage.
